export type Lang = "en" | "zh";

export const LANGS: { key: Lang; label: string }[] = [
  { key: "en", label: "EN" },
  { key: "zh", label: "中文" },
];

/** English is the default / fallback language. */
export const DEFAULT_LANG: Lang = "en";

/**
 * Pick the best supported language from an ordered list of BCP-47 tags
 * (e.g. navigator.languages: ["zh-CN", "en-US"]). Returns the first tag that
 * maps to a supported language, falling back to English when nothing matches.
 */
export function matchLang(tags: readonly string[] | undefined): Lang {
  if (!tags) return DEFAULT_LANG;
  for (const tag of tags) {
    const lower = tag.toLowerCase();
    if (lower === "zh" || lower.startsWith("zh-") || lower.startsWith("zh_")) {
      return "zh";
    }
    if (lower === "en" || lower.startsWith("en-") || lower.startsWith("en_")) {
      return "en";
    }
  }
  return DEFAULT_LANG;
}

export const LOCALE: Record<Lang, string> = {
  en: "en-US",
  zh: "zh-CN",
};

export const LANG_NAME: Record<Lang, string> = {
  en: "English",
  zh: "Chinese (简体中文)",
};

type Dict = {
  liveBadge: string;
  titleMain: string;
  titleSuffix: string;
  tagline: string;
  updatedPrefix: string;
  refresh: string;
  refreshing: string;
  groups: string;
  bracket: string;
  loading: string;
  retry: string;
  footerPre: string;
  footerPost: string;
  ft: string;
  predict: string;
  tbd: string;
  model: string;
  sonnetDesc: string;
  opusDesc: string;
  predictBtn: string;
  predicting: string;
  stepResearching: string;
  stepSearching: string;
  stepFinalizing: string;
  savedNote: string;
  winnerPrefix: string;
  drawText: string;
  confidence: string;
  reasoning: string;
  rankLabel: string;
  keyFactorsLabel: string;
  h2hLabel: string;
  squadLabel: string;
  sourcesLabel: string;
  viaPrefix: string;
  viaSuffix: string;
  teamCol: string;
  pCol: string;
  gdCol: string;
  ptsCol: string;
  teamsTbd: string;
  bracketEmpty: string;
  vs: string;
};

export const DICT: Record<Lang, Dict> = {
  en: {
    liveBadge: "Live · Canada · USA · Mexico",
    titleMain: "World Cup 2026",
    titleSuffix: "Predictor",
    tagline:
      "Live schedule & bracket. Pick an upcoming match and let Claude call the scoreline.",
    updatedPrefix: "Updated ",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    groups: "Groups",
    bracket: "Bracket",
    loading: "Loading schedule…",
    retry: "Retry",
    footerPre: "Schedule data from the public ",
    footerPost: " dataset. Predictions generated by Claude.",
    ft: "FT",
    predict: "Predict",
    tbd: "TBD",
    model: "Model",
    sonnetDesc: "Fast, balanced predictions",
    opusDesc: "Deepest reasoning",
    predictBtn: "Predict result",
    predicting: "Predicting…",
    stepResearching: "Researching both teams…",
    stepSearching: "Searching: ",
    stepFinalizing: "Analyzing findings & finalizing prediction…",
    savedNote: "Showing a saved prediction for this match & model.",
    winnerPrefix: "Winner: ",
    drawText: "Predicted draw",
    confidence: "Confidence",
    reasoning: "Reasoning",
    rankLabel: "FIFA rank",
    keyFactorsLabel: "Key factors",
    h2hLabel: "Head-to-head",
    squadLabel: "Squad & availability",
    sourcesLabel: "Sources",
    viaPrefix: "via ",
    viaSuffix: "",
    teamCol: "Team",
    pCol: "P",
    gdCol: "GD",
    ptsCol: "Pts",
    teamsTbd: "Teams TBD",
    bracketEmpty: "The knockout bracket has not been drawn yet.",
    vs: "vs",
  },
  zh: {
    liveBadge: "进行中 · 加拿大 · 美国 · 墨西哥",
    titleMain: "2026 世界杯",
    titleSuffix: "预测器",
    tagline: "实时赛程与对阵图。选择一场即将进行的比赛，让 Claude 预测比分。",
    updatedPrefix: "更新于 ",
    refresh: "刷新",
    refreshing: "刷新中…",
    groups: "小组赛",
    bracket: "淘汰赛",
    loading: "正在加载赛程…",
    retry: "重试",
    footerPre: "赛程数据来自公开的 ",
    footerPost: " 数据集，预测由 Claude 生成。",
    ft: "完场",
    predict: "预测",
    tbd: "待定",
    model: "模型",
    sonnetDesc: "快速、均衡的预测",
    opusDesc: "最强推理能力",
    predictBtn: "预测比分",
    predicting: "预测中…",
    stepResearching: "正在研究双方球队…",
    stepSearching: "搜索：",
    stepFinalizing: "正在分析资料并生成预测…",
    savedNote: "显示该比赛与模型的已保存预测结果。",
    winnerPrefix: "胜者：",
    drawText: "预测为平局",
    confidence: "信心指数",
    reasoning: "分析理由",
    rankLabel: "FIFA 排名",
    keyFactorsLabel: "关键因素",
    h2hLabel: "历史交锋",
    squadLabel: "阵容与伤停",
    sourcesLabel: "信息来源",
    viaPrefix: "由 ",
    viaSuffix: " 生成",
    teamCol: "球队",
    pCol: "场",
    gdCol: "净胜",
    ptsCol: "积分",
    teamsTbd: "球队待定",
    bracketEmpty: "淘汰赛对阵尚未确定。",
    vs: "vs",
  },
};

const TEAM_ZH: Record<string, string> = {
  Algeria: "阿尔及利亚",
  Argentina: "阿根廷",
  Australia: "澳大利亚",
  Austria: "奥地利",
  Belgium: "比利时",
  "Bosnia & Herzegovina": "波黑",
  Brazil: "巴西",
  Canada: "加拿大",
  "Cape Verde": "佛得角",
  Colombia: "哥伦比亚",
  Croatia: "克罗地亚",
  "Curaçao": "库拉索",
  "Czech Republic": "捷克",
  "DR Congo": "刚果（金）",
  Ecuador: "厄瓜多尔",
  Egypt: "埃及",
  England: "英格兰",
  France: "法国",
  Germany: "德国",
  Ghana: "加纳",
  Haiti: "海地",
  Iran: "伊朗",
  Iraq: "伊拉克",
  "Ivory Coast": "科特迪瓦",
  Japan: "日本",
  Jordan: "约旦",
  Mexico: "墨西哥",
  Morocco: "摩洛哥",
  Netherlands: "荷兰",
  "New Zealand": "新西兰",
  Norway: "挪威",
  Panama: "巴拿马",
  Paraguay: "巴拉圭",
  Portugal: "葡萄牙",
  Qatar: "卡塔尔",
  "Saudi Arabia": "沙特阿拉伯",
  Scotland: "苏格兰",
  Senegal: "塞内加尔",
  "South Africa": "南非",
  "South Korea": "韩国",
  Spain: "西班牙",
  Sweden: "瑞典",
  Switzerland: "瑞士",
  Tunisia: "突尼斯",
  Turkey: "土耳其",
  USA: "美国",
  Uruguay: "乌拉圭",
  Uzbekistan: "乌兹别克斯坦",
};

const ROUND_ZH: Record<string, string> = {
  "Round of 32": "32 强",
  "Round of 16": "16 强",
  "Quarter-final": "四分之一决赛",
  "Semi-final": "半决赛",
  "Match for third place": "季军赛",
  Final: "决赛",
};

export function translateTeam(name: string, lang: Lang): string {
  if (lang === "en") return name;
  return TEAM_ZH[name] ?? name;
}

export function translateRound(round: string, lang: Lang): string {
  if (lang === "en") return round;
  return ROUND_ZH[round] ?? round;
}

export function translateGroup(group: string | null | undefined, lang: Lang): string {
  if (!group) return "";
  if (lang === "en") return group;
  const letter = group.replace(/[^A-Za-z]/g, "");
  return letter ? `${letter} 组` : group;
}
